import MainProvider from '@/components/MainProvider';
import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Header from '@/components/layout/Header';
import HeaderAndMenu from '@/components/layout/HeaderAndMenu';
import Script from 'next/script';

const poppins = Poppins({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Script src="https://applepay.cdn-apple.com/jsapi/v1/apple-pay-sdk.js"></Script>
        <MainProvider>
          <HeaderAndMenu />
          {children}
        </MainProvider>
      </body>
    </html>
  );
}
